### ISSUE TITLE
Notes aren't accessible after refresh

### ISSUE THREAD

**Issue by ghost** [prnvtripathi/KeepIt#1]
Notes aren't enabled for showing after a refresh
I would like to make them accessible even after a refresh.
## Solution 

I will use [redux-persist](https://github.com/rt2zz/redux-persist) to do this .

**Comment by ghost** [comment]
Hiii @prnvtripathi !!!
have a look

**Comment by prnvtripathi** [comment]
Thank you for opening the issue, you may work on it

**Comment by ghost** [comment]
It will take me day or two to complete . Thanks man @prnvtripathi  for collaborating cheers !!!  😊😊

**Comment by prnvtripathi** [comment]
Take your time and cheers 🤝🏻

**Comment by prnvtripathi** [comment]
No progress

**Comment by prnvtripathi** [comment]
Closing the issue
